# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 01:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
