# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-05-04 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import pessoas.models


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0002_auto_20180504_0152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=pessoas.models.upload_image_pessoa),
        ),
    ]
